### ISSUE TITLE
I couldn't receive the JS's response.

### ISSUE THREAD

**Issue by jkyin** [marcuswestin/WebViewJavascriptBridge#108]
When I make WebViewJavascriptBridge to a static library, I could not get js response. Why?

It works, If not to static library. But I need it as library. Can you help me?

**Comment by davyzhang** [comment]
Maybe a little bit late, but I ran into the same issue today. And I finally made my code work thanks to this post. The true reason is actually not the static lib or class, it is the way that I packed this class as part of framework. So the bundle path should be something like "Framework/xxx.framework/xxx.bundle"  instead of main bundle. Fortunately there's a resbundle parameter when init the class, which can carry my own bundle other than the default one. Great work.
