### ISSUE TITLE
How can I use the WVJB without reload ? (iOS) 

### ISSUE THREAD

**Issue by JoviZT001** [marcuswestin/WebViewJavascriptBridge#134]
When I use the WVJB to receive the data from JS. It can only worked once before reload my UIWebView. How to receive the data without reload?

**Comment by lokimeyburg** [comment]
Can give you more details? Have you checked out the demo that comes with the repo? It has a "reload" button and it works fine. Here's a video of it in action: http://cloud.loki.io/image/3l1z0M3l3T2W .You'll see I send messages, then I reload, and send messages again - it works.

**Comment by marcuswestin** [comment]
I believe this may be fixed in v5.0.1.

When you switch to the new version, please note that the API has changed. In particular, make sure that you use the javascript setup code, as it has changed: https://github.com/marcuswestin/WebViewJavascriptBridge#usage

If you are still having trouble when using v5.0.x, feel free to reopen.

Cheers!
