### ISSUE TITLE
Example code is not working when used with latest Cocoapod file

### ISSUE THREAD

**Issue by ahallora** [marcuswestin/WebViewJavascriptBridge#155]
I have added the cocoapod (http://cocoapods.org/pods/WebViewJavascriptBridge) to my project:
```
pod "WebViewJavascriptBridge", "~> 4.1.4"
```
I have used the example code found in https://github.com/marcuswestin/WebViewJavascriptBridge/tree/master/Example%20Apps/ExampleApp-iOS and have spent two hours now trying to figure out when the bridge doesn't work. The exampleApp.html comes up fine and the log shows the obj-c sending data off, but the calls are never received in the webview. 

As the example code was working I tried **removing the pod** and **manually drag the WebViewJavascriptBridge into my project** - and voila, it works! 

There must be something wrong with the files in your pod. Just FYI. :smile:

**Comment by lbj96347** [comment]
I suppose that this project's spec file is not matching the lastest code.When I installed 4.1.4 version,I checked my Pods > WebViewJavascriptBridge and just 'WebViewJavascriptBridge.h' existed.But 'WKWebViewJavascriptBridge.h' doesn't exist in the folder. :-(

**Comment by ancheng1114** [comment]
I had same issue with pod.

**Comment by fitch** [comment]
Has someone resolved this?

**Comment by lbj96347** [comment]
You can try 

    pod "WebViewJavascriptBridge", :head 

And get all source from this project.

**Comment by ancheng1114** [comment]
Cocoapod doesn't seem to work , i downloaded github code and copied and
pasted bridge code, then it worked nice.

On Thu, Dec 10, 2015 at 4:03 PM, CashLee <notifications@github.com> wrote:

> You can try
>
> pod "WebViewJavascriptBridge", :head
>
> And get all source from this project.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/marcuswestin/WebViewJavascriptBridge/issues/155#issuecomment-163628121>
> .
>



-- 
Head of iOS and Android Development
_________________________________

ZhongShan DaLian
Email ancheng@gp2u.com.au <james@gp2u.com.au>

**Comment by marcuswestin** [comment]
Hi guys,




I've been out of action for quite a while. I'm finally about to be able to take this back up again, and intend to resolve all the outstanding issues.




Sorry for all the inconveniences in the meantime!!



-- while mobile

**Comment by saraht129** [comment]
I spent numerous hours trying to make the bridge works too. I installed the framework with Cocoapod and followed every single code demonstrated in your Example, it just didn't work. 

At last I discovered that the bridge in my javascript was never initialized, the `WebViewJavascriptBridgeReady` event was never called. It turned out that the bundle path of `WebViewJavascriptBridge.js` is different when it's managed by Pods. You'll have to update the path to have the js file loads correctly in your Webview.

**Comment by marcuswestin** [comment]
Hi guys,

This should have been fixed in 4.1.5.

Note that the newest version is 5.0.1. If you switch to the new version, please note that the API has changed. In particular, make sure that you use the javascript setup code, as it has changed: https://github.com/marcuswestin/WebViewJavascriptBridge#usage

Cheers!
