### ISSUE TITLE
It can't respond objc action when the webView did not finish load

### ISSUE THREAD

**Issue by shanksHJKL** [marcuswestin/WebViewJavascriptBridge#156]
I have a question ,when the UIWebView including many pictures is loading, I call native objc function but it can not respond;only when the webView actually did finish load can I success call objc function. Is that right?

**Comment by marcuswestin** [comment]
I believe this may be fixed in v5.0.1.

When you switch to the new version, please note that the API has changed. In particular, make sure that you use the javascript setup code, as it has changed: https://github.com/marcuswestin/WebViewJavascriptBridge#usage

If you are still having trouble when using v5.0.x, feel free to reopen.

Cheers!
