### ISSUE TITLE
xcode7 issues  OBJC_CLASS_$_WKWebViewJavascriptBridge", referenced from...

### ISSUE THREAD

**Issue by Tomikes** [marcuswestin/WebViewJavascriptBridge#158]
i do this " Drag the WebViewJavascriptBridge folder into your project.
    In the dialog that appears, uncheck "Copy items into destination group's folder" and select "Create groups for any folders""
xcode tell me : (null): "_OBJC_CLASS_$_WKWebViewJavascriptBridge", referenced from:

**Comment by ahallora** [comment]
Same issue in #153  - please fix :)

**Comment by GeorgeYJL** [comment]
+1

**Comment by Tomikes** [comment]
thinks！

**Comment by isaacnotnwton** [comment]
+1 please fix :)

**Comment by marcuswestin** [comment]
@lokimeyburg: any thoughts on this?

@isaacnotnwton @Tomikes @GeorgeYJL @ahallora, how do I reproduce this?

**Comment by marcuswestin** [comment]
Comment from #153: 

"WKWebView is only available in iOS 8 and later (https://developer.apple.com/library/ios/documentation/WebKit/Reference/WKWebView_Ref/).

I believe the problem you're seeing is due to attempting to use WKWebViewJavascriptBridge.h in iOS 7 when you should be using WebViewJavascriptBridge.h.

Feel free to reopen if you think I got it wrong."

**Comment by proh0r** [comment]
I have to mention that linker Error is not related to any other answers in my case.
The issue was - that I didn't ad javascriptBridge files to compile sources
