### ISSUE TITLE
When I separate the 'ExampleApp.html' '<script></script>' to a single '.js' file, the demo cannot run successfully.

### ISSUE THREAD

**Issue by zbleftover** [marcuswestin/WebViewJavascriptBridge#160]
OSX Example demo, I separate 'ExampleApp.html'  '<script></script>' to a single '.js' file, like 'ExampleApp.js', then add '<script src='ExampleApp.js></script>'' at last of 'ExampleApp.html' body. But the demo cannot run successfully, can you help me figure out it, thanks.

**Comment by marcuswestin** [comment]
Hi @vontio,

Without a repro I won't be able to help you :(

If you create a PR with a failing test then I will definitely give you a hand (see https://github.com/marcuswestin/WebViewJavascriptBridge/blob/master/Tests/WebViewJavascriptBridgeTests/BridgeTests.m and https://github.com/marcuswestin/WebViewJavascriptBridge/blob/master/Tests/WebViewJavascriptBridgeTests/echo.html).

You could also create a PR with an example in `Example Apps` with the problem you're seeing in - that would definitely help me help you :)

I'll close this in the meantime since there's nothing I can do. Feel free to reopen with a repro or more information.

Cheers!
