### ISSUE TITLE
What dose the iframe do?

### ISSUE THREAD

**Issue by djyde** [marcuswestin/WebViewJavascriptBridge#163]
Hi, WebViewJavascriptBridge is cool. But I have an odd trouble.

There is an **ajax request (XHR)** in my website. When I inject the WebViewJavascriptBridge js code. The request was broken. 

https://github.com/marcuswestin/WebViewJavascriptBridge/blob/master/WebViewJavascriptBridge%2FWebViewJavascriptBridge.js.txt#L18

This is the relevant code. 

But what confuse me is, what is the iframe for? It seems that the iframe do nothing in the js code (Only set the `src`.)

Hope reply soon, thanks.

**Comment by guilhermebruzzi** [comment]
I have the same problem.

This bridge uses the src attribute to receive the javascript messages.

But for some reason the javascript bridge stops all requests after it receives the message: https://github.com/marcuswestin/WebViewJavascriptBridge/blob/master/WebViewJavascriptBridge/WKWebViewJavascriptBridge.m#L130

Without that line: "[webView stopLoading];" it works. But i don't know the extra impacts of that.

**Comment by lbj96347** [comment]
@djyde I have been working several days with you.That's very nice. :-) 

About the iFrame.WebViewJavascriptBridge uses it for injecting code(sendData or callHandler... to UIWebView/WKWebView.

As @guilhermebruzzi said,the bridge uses the src attribute to receive the javascript messages or send message.What ever UIWebView or WKWebView ,they uses     
	
	wvjbscheme://__WVJB_QUEUE_MESSAGE__
	
But why our code works well in UIWebView but failed in WKWebView? @guilhermebruzzi gave us a key point.

I go deep into code of the bridge.I found these delegate methods in UIWebView and WKWebView.

***UIWebView***

	- (BOOL)webView:(UIWebView *)webView shouldStartLoadWithRequest:(NSURLRequest *)request navigationType:(UIWebViewNavigationType)navigationType {
    	if (webView != _webView) { return YES; }
    	NSURL *url = [request URL];
    	__strong WVJB_WEBVIEW_DELEGATE_TYPE* strongDelegate = _webViewDelegate;
    	if ([_base isCorrectProcotocolScheme:url]) {
        	if ([_base isCorrectHost:url]) {
            	NSString *messageQueueString = [self _evaluateJavascript:[_base webViewJavascriptFetchQueyCommand]];
            	[_base flushMessageQueue:messageQueueString];
        	} else {
            	[_base logUnkownMessage:url];
        	}
        	return NO;
    	} else if (strongDelegate && [strongDelegate respondsToSelector:@selector(webView:shouldStartLoadWithRequest:navigationType:)]) {
        	return [strongDelegate webView:webView shouldStartLoadWithRequest:request navigationType:navigationType];
    	} else {
        	return YES;
    	}
	}

***WKWebView***

	- (void)webView:(WKWebView *)webView decidePolicyForNavigationAction:(WKNavigationAction *)navigationAction decisionHandler:(void (^)(WKNavigationActionPolicy))decisionHandler {
    	if (webView != _webView) { return; }
    	NSURL *url = navigationAction.request.URL;
    
    	NSLog(@"url is %@", url);
    
	    __strong typeof(_webViewDelegate) strongDelegate = _webViewDelegate;

    	if ([_base isCorrectProcotocolScheme:url]) {
        	if ([_base isCorrectHost:url]) {
            	[self WKFlushMessageQueue];
        	} else {
            	[_base logUnkownMessage:url];
        	}
        	[webView stopLoading];
    	}
    
    	if (strongDelegate && [strongDelegate respondsToSelector:@selector(webView:decidePolicyForNavigationAction:decisionHandler:)]) {
        	[_webViewDelegate webView:webView decidePolicyForNavigationAction:navigationAction decisionHandler:decisionHandler];
    	} else {
        	decisionHandler(WKNavigationActionPolicyAllow);
    	}
	}
	
  
Both of these methods do the same thing.The Author of bridge tried to avoid repeating inject 

	wvjbscheme://__WVJB_QUEUE_MESSAGE__
	
(the iFrame) or redundant Javascript actions of the bridge.

In UIWebView,

	webView:shouldStartLoadWithRequest:navigationType:

It means : sent before a web view begins loading a frame.That makes sense.

In WKWebView

	- webView:decidePolicyForNavigationAction:decisionHandler: 

It means : Decides whether to allow or cancel a navigation.

But 

	[webView stopLoading]
	
It canceled all navigation actions including css image loading Javascript new Image() or XMLHttpRequest ... I try to use break point to figure out this.

***If we use WKWebView,we couldn't do network requests with bridge actions together.***

I suppose that 
	
	[webView stopLoading] 
	
should be 

	decisionHandler(WKNavigationActionPolicyCancel)
	
Because after ***WKFlushMessageQueue*** we should do the right thing like UIWebView does,but not stop loading all resource in WKWebView.

@guilhermebruzzi every actions cross 

	wvjbscheme://__WVJB_QUEUE_MESSAGE__ 
	
would run 

	- webView:decidePolicyForNavigationAction:decisionHandler: 

without that line: "[webView stopLoading];" may cause some redundant Javascript actions I guess.

Hope @marcuswestin would see this. :-)

**Comment by marcuswestin** [comment]
@djyde cheers :)
