### ISSUE TITLE
I cannot see WKWebViewJavascriptBridge class when install with cocoapod.

### ISSUE THREAD

**Issue by Wangxiaotao** [marcuswestin/WebViewJavascriptBridge#167]
I use WebViewJavascriptBridge in my project with cocoapod, the pod file below

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'WebViewJavascriptBridge'

after i run pod install，i found that under WebViewJavascriptBridge directory there is only two files: 
WebViewJavascriptBridge.h
WebViewJavascriptBridge.m

and the WebViewJavascriptBridge class not seem.

can you support it in cocoapod?

**Comment by lbj96347** [comment]
@Wangxiaotao You can try : 

    pod 'WebViewJavascriptBridge' , :head

**Comment by Wangxiaotao** [comment]
@lbj96347  I try it but still not see WKWebViewJavascriptBridge file.

**Comment by Wangxiaotao** [comment]
@lbj96347  Thanks, it works!

**Comment by yimiaodaren** [comment]
@lbj96347 
why not release new version?  i would like use , '~> 4.1.4'

**Comment by marcuswestin** [comment]
Pod v4.1.5 published in 5a91baca0da8

**Comment by marcuswestin** [comment]
I believe this is fixed in v4.1.5.

If you switch to the newest version, v5.0.1, please note that the API has changed. In particular, make sure that you use the javascript setup code, as it has changed: https://github.com/marcuswestin/WebViewJavascriptBridge#usage

If you are still having trouble when using v5.0.x, feel free to reopen.

Cheers!
