### ISSUE TITLE
cookie not send with jquery ajax

### ISSUE THREAD

**Issue by vontio** [marcuswestin/WebViewJavascriptBridge#171]
1,set cookie before send ajax 
$.cookie("example", "foo");
2,send ajax
$.ajax
		url:	...
		type:	"GET"
		headers: ...
		data:...
3,cookie "example" not sent,but cookie set by server has sent

4,alert document.cookie ,"example" is there,but server cookie not show up in the alert

does WebViewJavascriptBridge store cookie somewhere else?

how to send a cookie from the client

**Comment by marcuswestin** [comment]
Hi @vontio,

Without a repro I won't be able to help you :(

If you create a failing test then I will definitely give you a hand (see https://github.com/marcuswestin/WebViewJavascriptBridge/blob/master/Tests/WebViewJavascriptBridgeTests/BridgeTests.m and https://github.com/marcuswestin/WebViewJavascriptBridge/blob/master/Tests/WebViewJavascriptBridgeTests/echo.html).

I'll close this in the meantime since there's nothing I can do. Feel free to reopen with a repro or more information.

Cheers!
