### ISSUE TITLE
UIWebView's delegate don't be triggered sometimes

### ISSUE THREAD

**Issue by FrankCYQ** [marcuswestin/WebViewJavascriptBridge#177]
I have set the webview's delegate, mostly it works fine,  but sometime when i load a request (the html data is normal), after "-(BOOL)webView:(UIWebView *)webView shouldStartLoadWithRequest:(NSURLRequest *)request navigationType:(UIWebViewNavigationType)navigationType"  reture YES, my webView do nothing , "-(void)webViewDidStartLoad:(UIWebView *)webView" don't be triggered, when i debug it into "WebViewJavascriptBridge.m" file , i found it did nothing just like my own delegate, and there will be a massage "void SendDelegateMessage(NSInvocation *): delegate (webView:decidePolicyForNavigationAction:request:frame:decisionListener:) failed to return after waiting 10 seconds. main run loop mode: kCFRunLoopDefaultMode ",  i'm sure that i do not do some long task to block main thread. I have no idea to figure this out , hope someone could help me ,Thank you very much!

**Comment by marcuswestin** [comment]
I believe this may be fixed in v5.0.1.

When you switch to the new version, please note that the API has changed. In particular, make sure that you use the javascript setup code, as it has changed: https://github.com/marcuswestin/WebViewJavascriptBridge#usage

If you are still having trouble when using v5.0.x, feel free to reopen.

Cheers!
