### ISSUE TITLE
Used in conjunction with NJKWebViewProgressView party will lose effect, how to solve?

### ISSUE THREAD

**Issue by zy645328270** [marcuswestin/WebViewJavascriptBridge#181]
Used in conjunction with NJKWebViewProgressView party will lose effect, how to solve?

**Comment by zy645328270** [comment]
Used in conjunction with NJKWebViewProgressView party will lose effect, how to solve?

**Comment by marcuswestin** [comment]
I believe this may be fixed in v5.0.1.

When you switch to the new version, please note that the API has changed. In particular, make sure that you use the javascript setup code, as it has changed: https://github.com/marcuswestin/WebViewJavascriptBridge#usage

If you are still having trouble when using v5.0.x, feel free to reopen.

Cheers!
