### ISSUE TITLE
SSL

### ISSUE THREAD

**Issue by purusho** [marcuswestin/WebViewJavascriptBridge#32]
It doesn't work with https

**Comment by huangqiaobo** [comment]
I use UIWebView+AFNetworking to load url request
 [webView loadRequest:self.URLRequest progress:nil success:nil failure:nil];
If the request is https, the WebViewJavascriptBridge will not work
But if I use [webView loadRequest:self.URLRequest] to load the Https request.
The WebViewJavascriptBridge is useful.
@purusho @marcuswestin 
Because I want to use AFNetworking to load the request, how can i fix it?
